name: Build & Test

on:
    pull_request:
        paths-ignore:
            - 'README.md'
    workflow_dispatch:

env:
    LC_APPLICATION_ID: nxfw-policy-tester

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v5
              with:
                  go-version-file: 'go.mod'

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v8
              with:
               version: v2.1.2

            - name: Build
              run: |
                  go build -ldflags='-s -w'

    sonatype:
        name: Sonatype Lifecycle
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: 'go.mod'

            - name: Generate go.list
              run: go list -f '{{define "M"}}{{.Path}} {{.Version}}{{end}}{{with .Module}}{{if not .Main}}{{if .Replace}}{{template "M" .Replace}}{{else}}{{template "M" .}}{{end}}{{end}}{{end}}' -compiled -deps| sort -u > go.list

            - name: Sonatype Lifecycle Evaluation
              id: evaluate
              uses: sonatype/actions/evaluate@v1
              with:
                  iq-server-url: ${{ vars.SONATYPE_PLATFORM_URL }}
                  username: ${{ secrets.SONATYPE_LIFECYCLE_USERNAME }}
                  password: ${{ secrets.SONATYPE_LIFECYCLE_PASSWORD }}
                  application-id: ${{ env.LC_APPLICATION_ID }}
                  scan-targets: 'go.list'